### PR TITLE
Added package.json for npm support

### PR DESCRIPTION
**Pull request by patrickpietens**
I've added NPM support because it's replacing bower for package management

### CODE REVIEW

**Comment by patrickpietens** [comment]
Please run `npm publish ./` after you accepted the pull request to publish the package to NPM

**Comment by snorpey** [comment]
hey @patrickpietens thanks for the pull request! sorry i missed the notification.

one question: i haven't published anything on npm yet, do i need to specify somewhere that this library only works in the browser at the moment?

**Comment by patrickpietens** [comment]
@snorpey No worries! 

Publishing to NPM is really simple. See the command I posted in an earlier post. All config is done through the `package.json`. As far as I know you don't need to specify the package is browser only.

**Comment by snorpey** [comment]
thank you!
unfortunately, https://www.npmjs.com/package/glitch-canvas is already taken. i'll try to figure things out with the current owner. if that fails, i'll probably pubish it under a different name.

**Pull request merged**
